const SDK_URL='https://esm.sh/@cloudflare/realtimekit?bundle';
export class ProximityVoice{
 constructor(game,name){this.game=game;this.name=name;this.meeting=null;this.enabled=false;this.muted=false;this.nodes=new Map;this.audioContext=null;this.el=this._ui();this._key=e=>{if(e.code==='KeyT'&&!e.repeat&&!typing()){e.preventDefault();this.toggleMute()}};addEventListener('keydown',this._key)}
 _ui(){const e=document.createElement('button');e.id='voice-status';e.type='button';e.textContent='🎙 VC接続中';e.title='T: マイクON/OFF';e.onclick=()=>this.toggleMute();document.body.appendChild(e);return e}
 async connect(){try{const r=await fetch('/api/voice/join?room=lake-1',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:this.name,playerId:this.game.mp?.id})});if(!r.ok)throw new Error(await r.text());const{token}=await r.json();const mod=await import(SDK_URL);const Client=mod.default||mod.RealtimeKitClient||mod;this.meeting=await Client.init({authToken:token,defaults:{audio:true,video:false}});this._bind();await this.meeting.join();this.enabled=true;this._render()}catch(e){console.warn('[voice]',e);this.el.textContent='🎙 VCなし';this.el.classList.add('error')}}
 _bind(){const j=this.meeting.participants.joined;j.on('participantJoined',p=>this._attach(p));j.on('participantLeft',p=>this._detach(p.id));j.on('audioUpdate',p=>p.audioEnabled?this._attach(p):this._detach(p.id));this.meeting.self.on('audioUpdate',({audioEnabled})=>{this.muted=!audioEnabled;this._render()});for(const p of(j.toArray?.()||[]))if(p.audioEnabled)this._attach(p)}
 async _attach(p){if(!p?.audioTrack||this.nodes.has(p.id))return;try{this.audioContext||=new AudioContext();if(this.audioContext.state==='suspended')await this.audioContext.resume();const source=this.audioContext.createMediaStreamSource(new MediaStream([p.audioTrack])),gain=this.audioContext.createGain(),pan=this.audioContext.createStereoPanner();source.connect(gain).connect(pan).connect(this.audioContext.destination);this.nodes.set(p.id,{source,gain,pan,p})}catch(e){console.warn('[voice attach]',e)}}
 _detach(id){const n=this.nodes.get(id);if(!n)return;try{n.source.disconnect();n.gain.disconnect();n.pan.disconnect()}catch{}this.nodes.delete(id)}
 update(){if(!this.enabled)return;const me=this.game.angler?.root?.position;if(!me)return;for(const n of this.nodes.values()){const pid=n.p.customParticipantId||n.p.custom_participant_id;const rp=this.game.remotePlayers?.map?.get(pid);const pos=rp?.angler?.root?.position;if(!pos){n.gain.gain.value=0;continue}const dx=pos.x-me.x,dz=pos.z-me.z,d=Math.hypot(dx,dz),v=d<=8?1:d>=40?0:1-(d-8)/32;n.gain.gain.value=v*v;const yaw=this.game.angler?.yaw||0,rightX=Math.cos(yaw),rightZ=-Math.sin(yaw);n.pan.pan.value=d>.001?Math.max(-1,Math.min(1,(dx*rightX+dz*rightZ)/d)):0}}
 async toggleMute(){if(!this.meeting)return;try{this.meeting.self.audioEnabled?await this.meeting.self.disableAudio():await this.meeting.self.enableAudio()}catch(e){console.warn('[voice mute]',e)}}
 _render(){this.muted=!this.meeting?.self?.audioEnabled;this.el.textContent=this.muted?'🔇 VC OFF':'🎙 VC ON';this.el.classList.toggle('muted',this.muted)}
 async close(){removeEventListener('keydown',this._key);for(const id of[...this.nodes.keys()])this._detach(id);try{await this.meeting?.leave()}catch{}try{await this.audioContext?.close()}catch{}this.el.remove()}}
function typing(){const e=document.activeElement;return e&&(e.tagName==='INPUT'||e.tagName==='TEXTAREA'||e.isContentEditable)}
