import { makeLake } from '../../src/lakefield.js';
import { REAL_FISH, GEAR, rollLength, rollAlbino } from '../../src/data.js';
import { pickSpecies, speciesWeight } from '../../src/fishing/simulation/rules.js';
import {
  FISH_APPROACH_SPEED_MUL, FISH_NIBBLE_SPEED_MUL, approachRadius, wanderSpeedMul,
  nibbleTarget, pickWanderTarget, steerVelocity, startleDuration, startleTarget, clampFishDepth,
} from '../../src/fishing/simulation/motion.js';
import { nextWeatherKey, nextWeatherHours, initialWeatherHours } from '../../src/fishing/simulation/weather.js';
import { timeBand } from '../../src/util.js';

const SEED=123456789,TICK=.1,BASE_FISH=18,PER_EXTRA_PLAYER=8,MAX_FISH=50,ACTIVE_R=72,DESPAWN_R=92,APPROACH_R=30;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const speciesById=id=>REAL_FISH.find(sp=>sp.id===id),baitById=id=>GEAR.bait.find(b=>b.id===id)||GEAR.bait[0],rodById=id=>GEAR.rod.find(r=>r.id===id)||GEAR.rod[0];
export class SharedWorld{
constructor(){this.lake=makeLake(SEED);this.fishes=new Map;this.baits=new Map;this.seq=1;this.weather='clear';this.weatherHours=initialWeatherHours()}
targetCount(players){return Math.min(MAX_FISH,BASE_FISH+Math.max(0,players.length-1)*PER_EXTRA_PLAYER)}
_worldHour(){for(const b of this.baits.values())if(Number.isFinite(b.hour))return b.hour;return 12}
spawnNear(players){if(!players.length)return null;for(let tries=0;tries<30;tries++){const p=players[Math.floor(Math.random()*players.length)];if(!Number.isFinite(p.x)||!Number.isFinite(p.z)||p.fresh)continue;const a=rand(0,Math.PI*2),r=rand(10,ACTIVE_R),x=p.x+Math.cos(a)*r,z=p.z+Math.sin(a)*r,depth=this.lake.depthAt(x,z);if(depth<.8)continue;const sp=pickSpecies({depth,band:timeBand(this._worldHour()),weather:this.weather});if(!sp)continue;const length=rollLength(sp),fishDepth=clamp(rand(sp.depth[0],Math.min(sp.depth[1],depth-.35)),.35,Math.max(.4,depth-.35)),id=`f${this.seq++}`;this.fishes.set(id,{id,speciesId:sp.id,species:sp,length,albino:rollAlbino(sp),x,y:-fishDepth,z,vx:0,vy:0,vz:0,tx:x,ty:-fishDepth,tz:z,depthBias:Math.random(),state:'swimming',targetBaitId:null,ownerPlayerId:null,turnAt:0,stateAt:Date.now(),phase:rand(0,10),startleUntil:0});return this.fishes.get(id)}return null}
setBait(playerId,bait){if(!bait){this.baits.delete(playerId);return}const x=+bait.x,y=+bait.y,z=+bait.z;if(![x,y,z].every(Number.isFinite)||Math.abs(x)>500||Math.abs(z)>500||y>2||y< -60)return;const acc=clamp(+bait.castAcc||0,0,1),power=clamp(+bait.castPower||0,0,1),now=Date.now(),radius=1+(3.2+power*2-1)*(1-acc),sec=.8+(5-.8)*(1-acc);for(const f of this.fishes.values()){if(f.state!=='swimming'||Math.hypot(f.x-x,f.z-z)>radius)continue;f.startleUntil=now+startleDuration(sec)*1000;const t=startleTarget(f,x,z);f.tx=t.x;f.ty=t.y;f.tz=t.z;f.turnAt=now+2000}this.baits.set(playerId,{id:`b:${playerId}`,playerId,x,y,z,baitType:String(bait.baitType||'').slice(0,24),rigLayer:String(bait.rigLayer||'').slice(0,12),rodType:String(bait.rodType||'').slice(0,16),level:clamp(+bait.level||1,1,99),bed:['sand','rock','mud'].includes(bait.bed)?bait.bed:null,nearStruct:!!bait.nearStruct,hour:Number.isFinite(+bait.hour)?+bait.hour:null,at:now})}
hook(playerId,fishId){const f=this.fishes.get(fishId);if(!f||f.ownerPlayerId!==playerId||f.state!=='reserved')return false;f.state='hooked';f.stateAt=Date.now();return true}
fightUpdate(playerId,fishId,pos){const f=this.fishes.get(fishId);if(!f||f.ownerPlayerId!==playerId||f.state!=='hooked')return;const x=+pos.x,y=+pos.y,z=+pos.z;if([x,y,z].every(Number.isFinite)){f.x=x;f.y=y;f.z=z}}
endFight(playerId,fishId,result){const f=this.fishes.get(fishId);if(!f||f.ownerPlayerId!==playerId)return null;if(result==='caught'){this.fishes.delete(fishId);this.baits.delete(playerId);return{removed:true,fish:f}}f.state='swimming';f.ownerPlayerId=null;f.targetBaitId=null;f.stateAt=Date.now();f.turnAt=0;return{removed:false,fish:f}}
dropPlayer(playerId){this.baits.delete(playerId);for(const f of this.fishes.values())if(f.ownerPlayerId===playerId){f.ownerPlayerId=null;f.targetBaitId=null;f.state='swimming';f.stateAt=Date.now()}}
_baitWeight(f,bait){const sp=f.species||speciesById(f.speciesId);if(!sp)return 0;const nearSpecies=new Set;for(const other of this.fishes.values())if(other.state==='swimming'&&Math.hypot(other.x-bait.x,other.z-bait.z)<18)nearSpecies.add(other.speciesId);return speciesWeight(sp,{depth:this.lake.depthAt(bait.x,bait.z),band:timeBand(bait.hour??this._worldHour()),weather:this.weather,useBait:true,bait:baitById(bait.baitType),layer:bait.rigLayer,bed:bait.bed,nearStruct:bait.nearStruct,nearSpecies,rodAttract:rodById(bait.rodType).attract,level:bait.level})}
_move(f,target,mul){const v=steerVelocity(f,target,mul,TICK);f.vx=v.vx;f.vy=v.vy;f.vz=v.vz;f.x+=f.vx*TICK;f.y+=f.vy*TICK;f.z+=f.vz*TICK;const c=clampFishDepth({x:f.x,y:f.y,z:f.z,vy:f.vy,length:f.length,terrain:this.lake,surfaceY:0});f.y=c.y;f.vy=c.vy;return v.dist}
tick(players){const now=Date.now(),hour=this._worldHour();this.weatherHours-=TICK/60;if(this.weatherHours<=0){this.weather=nextWeatherKey(this.weather);this.weatherHours=nextWeatherHours()}const wanted=this.targetCount(players);while(this.fishes.size<wanted)if(!this.spawnNear(players))break;const occupied=new Set;for(const f of this.fishes.values())if(f.targetBaitId&&['approaching','reserved','hooked'].includes(f.state))occupied.add(f.targetBaitId);for(const f of this.fishes.values()){if(f.state==='hooked')continue;if(f.state==='reserved'){const bait=[...this.baits.values()].find(b=>b.id===f.targetBaitId);if(!bait||now-f.stateAt>7000){occupied.delete(f.targetBaitId);f.state='swimming';f.ownerPlayerId=null;f.targetBaitId=null;continue}this._move(f,nibbleTarget(bait,f.phase,now/1000),FISH_NIBBLE_SPEED_MUL);continue}if(f.state==='approaching'){const bait=[...this.baits.values()].find(b=>b.id===f.targetBaitId);if(!bait){occupied.delete(f.targetBaitId);f.state='swimming';f.targetBaitId=null}else{const d=this._move(f,bait,FISH_APPROACH_SPEED_MUL);if(d<=approachRadius(f.length)){f.state='reserved';f.ownerPlayerId=bait.playerId;f.stateAt=now}else if(now-f.stateAt>18000){occupied.delete(f.targetBaitId);f.state='swimming';f.targetBaitId=null}}continue}const targetDist=Math.hypot(f.x-f.tx,f.y-f.ty,f.z-f.tz);if(now>=f.turnAt||targetDist<1.2){const t=pickWanderTarget({fish:f,terrain:this.lake,band:timeBand(hour)});f.tx=t.x;f.ty=t.y;f.tz=t.z;f.depthBias=t.depthBias;f.turnAt=now+rand(2500,6000)}this._move(f,{x:f.tx,y:f.ty,z:f.tz},wanderSpeedMul(f.phase,now/1000,now<f.startleUntil));if(now<f.startleUntil)continue;let best=null,bestScore=0;for(const bait of this.baits.values()){if(occupied.has(bait.id))continue;const d=Math.hypot(f.x-bait.x,f.z-bait.z);if(d>=APPROACH_R)continue;const w=this._baitWeight(f,bait);if(w<=0)continue;const score=w/(4+d);if(score>bestScore){best=bait;bestScore=score}}if(best&&Math.random()<TICK*.10*Math.min(2,Math.max(.15,bestScore/8))){f.state='approaching';f.targetBaitId=best.id;f.ownerPlayerId=null;f.stateAt=now;occupied.add(best.id)}}for(const[id,f]of this.fishes){if(this.fishes.size<=wanted||f.state!=='swimming')continue;const near=players.some(p=>!p.fresh&&Math.hypot(f.x-p.x,f.z-p.z)<=DESPAWN_R);if(!near)this.fishes.delete(id)}}
snapshot(){return[...this.fishes.values()].map(f=>({id:f.id,speciesId:f.speciesId,length:f.length,albino:f.albino,x:+f.x.toFixed(2),y:+f.y.toFixed(2),z:+f.z.toFixed(2),state:f.state,targetBaitId:f.targetBaitId,ownerPlayerId:f.ownerPlayerId}))}
}
